services:
  mariadb:
    image: mariadb:latest
    volumes:
      - m223_project_mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret123
      - MYSQL_DATABASE=minitwitter
      - MYSQL_USER=minitwitter
      - MYSQL_PASSWORD=supersecret123
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=supersecret123
    ports:
      - 9200:80

volumes:
  m223_project_mariadb:
